### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by yzlicloud** [baiksung/ALFA#3]
I put the miniimagenet in the folder "datasets" folder, the miniimagenet  dataset include "images" and "test.csv" and "train.csv", "val.csv". but  report an error, where should i put the dataset . thank you!

**Comment by baiksung** [comment]
Can you provide more details on where you got the miniImageNet dataset and what the error is? Did you follow the directions provided by [MAML++ public code](https://github.com/AntreasAntoniou/HowToTrainYourMAMLPytorch)?
