### ISSUE TITLE
MAML performance is not reproducible

### ISSUE THREAD

**Issue by yelobean** [baiksung/ALFA#5]
I'm sorry to bother you, but I cannot reproduce the MAML performance of your paper when the backbone is 'ResNet12'.

To train MAML with ResNet12, I ran the script 'experiment_scripts/alfa+maml_resnet12.sh' after modifying 'alfa:false' in 'experiment_config/alfa+maml_resnet12.json'.
However, I only got 51% accuracy, which is too different from your performance(58%).

Could you please let me know what part I should correct?

**Comment by baiksung** [comment]
I'm assuming you are referring to 5-way 1-shot performance?
You should run on a single GPU with `batch size` set to `4` and `num_samples_per_class` set to `1` other than setting `alfa:false` in `experiment_config/alfa+maml_resnet12.json`.

Best,
Sungyong

**Comment by yelobean** [comment]
Thank you for the fast reply!

I will try it!

Best regards,
Duhun.
